export const SECTORS = [
  { value: '', label: 'All' },
  { value: 'Government', label: 'Government' },
  { value: 'Information Technology', label: 'Information Technology' },
  { value: 'Energy', label: 'Energy' },
  { value: 'Environment', label: 'Environment' },
  { value: 'Security', label: 'Security' },
  { value: 'Retail', label: 'Retail' },
  { value: 'Construction', label: 'Construction' },
  { value: 'Manufacturing', label: 'Manufacturing' },
  { value: 'Financial Services', label: 'Financial Services' },
  { value: 'Support Services', label: 'Support Services' },
  { value: 'Tourism & Hospitality', label: 'Tourism & Hospitality' },
  { value: 'Water', label: 'Water' },
  { value: 'Aerospace & Defence', label: 'Aerospace & Defence' },
  { value: 'Automotive', label: 'Automotive' },
  { value: 'Transport', label: 'Transport' },
  { value: 'Healthcare', label: 'Healthcare' },
  { value: 'Food & Agriculture', label: 'Food & Agriculture' },
  { value: 'Media & Entertainment', label: 'Media & Entertainment' }
];

  
export const TOPICS = [
  { value: '', label: 'All' },
  { value: 'War', label: 'War' },
  { value: 'Capital', label: 'Capital' },
  { value: 'Money', label: 'Money' },
  { value: 'GDP', label: 'GDP' },
  { value: 'Tourist', label: 'Tourist' },
  { value: 'Risk', label: 'Risk' },
  { value: 'Biofuel', label: 'Biofuel' },
  { value: 'Oil', label: 'Oil' },
  { value: 'Consumption', label: 'Consumption' },
  { value: 'Vehicle', label: 'Vehicle' },
  { value: 'Growth', label: 'Growth' },
  { value: 'Workforce', label: 'Workforce' },
  { value: 'Change', label: 'Change' },
  { value: 'Inflation', label: 'Inflation' },
  { value: 'Infrastructure', label: 'Infrastructure' },
  { value: 'Carbon', label: 'Carbon' },
  { value: 'Shale Gas', label: 'Shale Gas' },
  { value: 'Work', label: 'Work' },
  { value: 'Finance', label: 'Finance' },
  { value: 'Building', label: 'Building' },
  { value: 'Clothing', label: 'Clothing' },
  { value: 'Shortage', label: 'Shortage' },
  { value: 'Tax', label: 'Tax' },
  { value: 'Robot', label: 'Robot' },
  { value: 'Production', label: 'Production' },
  { value: 'Economic Growth', label: 'Economic Growth' },
  { value: 'Terrorism', label: 'Terrorism' },
  { value: 'Information', label: 'Information' },
  { value: '3D', label: '3D' },
  { value: 'Population', label: 'Population' },
  { value: 'Fossil Fuel', label: 'Fossil Fuel' },
  { value: 'Storm', label: 'Storm' },
  { value: 'Food', label: 'Food' },
  { value: 'Aquaculture', label: 'Aquaculture' },
  { value: 'Election', label: 'Election' },
  { value: 'Coal', label: 'Coal' },
  { value: 'Software', label: 'Software' },
  { value: 'Data', label: 'Data' },
  { value: 'Market', label: 'Market' },
  { value: 'Interest Rate', label: 'Interest Rate' },
  { value: 'Peak Oil', label: 'Peak Oil' },
  { value: 'Brexit', label: 'Brexit' },
  { value: 'Politics', label: 'Politics' },
  { value: 'Emission', label: 'Emission' },
  { value: 'Pollution', label: 'Pollution' },
  { value: 'Ice', label: 'Ice' },
  { value: 'Resource', label: 'Resource' },
  { value: 'Automaker', label: 'Automaker' },
  { value: 'Climate', label: 'Climate' },
  { value: 'Demand', label: 'Demand' },
  { value: 'Worker', label: 'Worker' },
  { value: 'Tension', label: 'Tension' },
  { value: 'Business', label: 'Business' },
  { value: 'Fracking', label: 'Fracking' },
  { value: 'Gamification', label: 'Gamification' },
  { value: 'Communication', label: 'Communication' },
  { value: 'Crisis', label: 'Crisis' },
  { value: 'Gas', label: 'Gas' },
  { value: 'Artificial Intelligence', label: 'Artificial Intelligence' },
  { value: 'Investment', label: 'Investment' },
  { value: 'Material', label: 'Material' },
  { value: 'Economy', label: 'Economy' },
  { value: 'Technology', label: 'Technology' },
  { value: 'Debt', label: 'Debt' },
  { value: 'Factory', label: 'Factory' },
  { value: 'Export', label: 'Export' },
  { value: 'Bank', label: 'Bank' },
  { value: 'Gasoline', label: 'Gasoline' },
  { value: 'Trade', label: 'Trade' },
  { value: 'Security', label: 'Security' },
  { value: 'Electricity', label: 'Electricity' },
  { value: 'Water', label: 'Water' },
  { value: 'Energy', label: 'Energy' },
  { value: 'Transportation', label: 'Transportation' },
  { value: 'Transport', label: 'Transport' },
  { value: 'Farm', label: 'Farm' },
  { value: 'Unemployment', label: 'Unemployment' },
  { value: 'Agriculture', label: 'Agriculture' },
  { value: 'Plastic', label: 'Plastic' },
  { value: 'Economic', label: 'Economic' },
  { value: 'Revenue', label: 'Revenue' },
  { value: 'Power', label: 'Power' },
  { value: 'Nuclear', label: 'Nuclear' },
  { value: 'Battery', label: 'Battery' },
  { value: 'Car', label: 'Car' },
  { value: 'Climate Change', label: 'Climate Change' },
  { value: 'Wealth', label: 'Wealth' },
  { value: 'Greenhouse Gas', label: 'Greenhouse Gas' },
  { value: 'Policy', label: 'Policy' },
  { value: 'Strategy', label: 'Strategy' },
  { value: 'Industry', label: 'Industry' },
  { value: 'Government', label: 'Government' },
  { value: 'Administration', label: 'Administration' },
  { value: 'Consumer', label: 'Consumer' },
  { value: 'City', label: 'City' },
  { value: 'Washington', label: 'Washington' },
  { value: 'Asylum', label: 'Asylum' }
];

  
export const REGIONS = [
  { value: '', label: 'All' },
  { value: 'Eastern Asia', label: 'Eastern Asia' },
  { value: 'Southern Africa', label: 'Southern Africa' },
  { value: 'Northern America', label: 'Northern America' },
  { value: 'Eastern Europe', label: 'Eastern Europe' },
  { value: 'Central America', label: 'Central America' },
  { value: 'Western Africa', label: 'Western Africa' },
  { value: 'Europe', label: 'Europe' },
  { value: 'South America', label: 'South America' },
  { value: 'Western Asia', label: 'Western Asia' },
  { value: 'Northern Africa', label: 'Northern Africa' },
  { value: 'Central Asia', label: 'Central Asia' },
  { value: 'Northern Europe', label: 'Northern Europe' },
  { value: 'Southern Asia', label: 'Southern Asia' },
  { value: 'Africa', label: 'Africa' },
  { value: 'South-Eastern Asia', label: 'South-Eastern Asia' },
  { value: 'World', label: 'World' },
  { value: 'Western Europe', label: 'Western Europe' },
  { value: 'Eastern Africa', label: 'Eastern Africa' },
  { value: 'Central Africa', label: 'Central Africa' },
  { value: 'Southern Europe', label: 'Southern Europe' },
  { value: 'Oceania', label: 'Oceania' }
];

  
export const PESTLE = [
  { value: '', label: 'All' },
  { value: 'Industries', label: 'Industries' },
  { value: 'Lifestyles', label: 'Lifestyles' },
  { value: 'Healthcare', label: 'Healthcare' },
  { value: 'Economic', label: 'Economic' },
  { value: 'Political', label: 'Political' },
  { value: 'Environmental', label: 'Environmental' },
  { value: 'Technological', label: 'Technological' },
  { value: 'Organization', label: 'Organization' },
  { value: 'Social', label: 'Social' }
];

  
export const SOURCES = [
  { value: '', label: 'All' },
  { value: 'EIA', label: 'EIA' },
  { value: 'Sustainablebrands.com', label: 'Sustainablebrands.com' },
  { value: 'SBWire', label: 'SBWire' },
  { value: 'CleanTechnica', label: 'CleanTechnica' },
  { value: 'TRAC News', label: 'TRAC News' },
  { value: 'Vanguard News', label: 'Vanguard News' },
  { value: 'Abq', label: 'Abq' },
  { value: 'WSJ', label: 'WSJ' },
  { value: 'Reuters', label: 'Reuters' },
  { value: 'Star Tribune', label: 'Star Tribune' },
  { value: 'EV Obsession', label: 'EV Obsession' },
  { value: 'creamermedia', label: 'creamermedia' },
  { value: 'Resilience', label: 'Resilience' },
  { value: 'TheNews.NG', label: 'TheNews.NG' },
  { value: 'Future Timeline', label: 'Future Timeline' },
  { value: 'Wells Fargo', label: 'Wells Fargo' },
  { value: 'MRC', label: 'MRC' },
  { value: 'Phys Org', label: 'Phys Org' },
  { value: 'VOA', label: 'VOA' },
  { value: 'polymerspaintcolourjournal', label: 'polymerspaintcolourjournal' },
  { value: 'Global Money Trends', label: 'Global Money Trends' },
  { value: 'Adam Curry', label: 'Adam Curry' },
  { value: 'Newsweek', label: 'Newsweek' },
  { value: 'Edge and Odds', label: 'Edge and Odds' },
  { value: 'Lawfare', label: 'Lawfare' },
  { value: 'The Guardian', label: 'The Guardian' },
  { value: 'Tactical Investor', label: 'Tactical Investor' },
  { value: 'newscientist', label: 'newscientist' },
  { value: 'THISDAY LIVE', label: 'THISDAY LIVE' },
  { value: 'valburyresearch', label: 'valburyresearch' },
  { value: 'veteranstoday', label: 'veteranstoday' },
  { value: 'Climate Change News', label: 'Climate Change News' },
  { value: 'CDC', label: 'CDC' },
  { value: 'TheCable', label: 'TheCable' },
  { value: 'Washington Post', label: 'Washington Post' },
  { value: 'Middle East Online', label: 'Middle East Online' },
  { value: 'OPEC', label: 'OPEC' },
  { value: 'World Bank Group', label: 'World Bank Group' },
  { value: 'Mast', label: 'Mast' },
  { value: 'Futurity', label: 'Futurity' },
  { value: 'Investopedia', label: 'Investopedia' },
  { value: 'Cars.co.za', label: 'Cars.co.za' },
  { value: 'GreenBiz', label: 'GreenBiz' },
  { value: 'Predictive Analytics Times', label: 'Predictive Analytics Times' },
  { value: 'Smart Grid Observer', label: 'Smart Grid Observer' },
  { value: 'Yes Bank', label: 'Yes Bank' },
  { value: 'Cushman & Wakefield', label: 'Cushman & Wakefield' },
  { value: 'European Central Bank', label: 'European Central Bank' },
  { value: 'Verisk Maplecroft', label: 'Verisk Maplecroft' },
  { value: 'Arangkada Philippines', label: 'Arangkada Philippines' },
  { value: 'Climate News Network', label: 'Climate News Network' },
  { value: 'watercanada', label: 'watercanada' },
  { value: 'dailyquiddity', label: 'dailyquiddity' },
  { value: 'portfolioticker', label: 'portfolioticker' },
  { value: 'maltawinds.com', label: 'maltawinds.com' },
  { value: 'The Ticker Tape', label: 'The Ticker Tape' },
  { value: 'Tech Times', label: 'Tech Times' },
  { value: 'Hardin Tibbs', label: 'Hardin Tibbs' },
  { value: 'Seeking Alpha', label: 'Seeking Alpha' },
  { value: 'FX Empire', label: 'FX Empire' },
  { value: 'europeanclimate', label: 'europeanclimate' },
  { value: 'ebrd', label: 'ebrd' },
  { value: 'University of Latvia', label: 'University of Latvia' },
  { value: 'The Arab Gulf States Institute Washington', label: 'The Arab Gulf States Institute Washington' },
  { value: 'idc-community', label: 'idc-community' },
  { value: 'BBC News Technology', label: 'BBC News Technology' },
  { value: 'Justmeans', label: 'Justmeans' },
  { value: 'www.narendramodi.in', label: 'www.narendramodi.in' },
  { value: 'Nexus Conference', label: 'Nexus Conference' },
  { value: 'PDQFX news', label: 'PDQFX news' },
  { value: 'The Next Web', label: 'The Next Web' },
  { value: 'EPS News', label: 'EPS News' },
  { value: 'Freedonia', label: 'Freedonia' },
  { value: 'Society of Motor Manufacturers and Traders (SMMT)', label: 'Society of Motor Manufacturers and Traders (SMMT)' },
  { value: 'The Globe and Mail', label: 'The Globe and Mail' },
  { value: 'No 2 Nuclear Power', label: 'No 2 Nuclear Power' },
  { value: 'Countries.com Global Content', label: 'Countries.com Global Content' },
  { value: 'World Energy News', label: 'World Energy News' },
  { value: 'CAFrackFacts', label: 'CAFrackFacts' },
  { value: 'ID TECH INDEX', label: 'ID TECH INDEX' },
  { value: 'Scania Group', label: 'Scania Group' },
  { value: 'Futureseek Link Digest', label: 'Futureseek Link Digest' },
  { value: 'therobotreport', label: 'therobotreport' },
  { value: 'globalfueleconomy', label: 'globalfueleconomy' },
  { value: 'unian', label: 'unian' },
  { value: 'Nanotechnology Innovation', label: 'Nanotechnology Innovation' },
  { value: 'platts', label: 'platts' },
  { value: 'CNBC', label: 'CNBC' },
  { value: 'gasstrategies', label: 'gasstrategies' },
  { value: 'IISS', label: 'IISS' },
  { value: 'arabellaadvisors', label: 'arabellaadvisors' },
  { value: 'MENA-Forum', label: 'MENA-Forum' },
  { value: 'AMERICAN COUNCIL ON SCIENCE AND HEALTH', label: 'AMERICAN COUNCIL ON SCIENCE AND HEALTH' },
  { value: 'News', label: 'News' },
  { value: 'njc-cnm', label: 'njc-cnm' },
  { value: 'Common Dreams', label: 'Common Dreams' },
  { value: 'conferenceseries', label: 'conferenceseries' },
  { value: 'GlobalMeatNews.com', label: 'GlobalMeatNews.com' },
  { value: 'Euromoney', label: 'Euromoney' },
  { value: 'Interior Design', label: 'Interior Design' },
  { value: 'African Development Bank', label: 'African Development Bank' },
  { value: 'Science News', label: 'Science News' },
  { value: 'National Geographic Society (blogs)', label: 'National Geographic Society (blogs)' },
  { value: 'satprnews', label: 'satprnews' },
  { value: 'clientadvisoryservices', label: 'clientadvisoryservices' },
  { value: 'OklahomaMinerals.com', label: 'OklahomaMinerals.com' },
  { value: 'Science Daily', label: 'Science Daily' },
  { value: 'UNESCO', label: 'UNESCO' },
  { value: 'Resilience', label: 'Resilience' },
  { value: 'Mind Commerce', label: 'Mind Commerce' },
  { value: 'VITA Technologies', label: 'VITA Technologies' },
  { value: 'atradius', label: 'atradius' },
  { value: 'energyglobal', label: 'energyglobal' },
  { value: 'bankofcanada', label: 'bankofcanada' },
  { value: 'Business Standard', label: 'Business Standard' },
  { value: 'Slinking Toward Retirement', label: 'Slinking Toward Retirement' },
  { value: 'Strategy & Formerly Booz & Company', label: 'Strategy & Formerly Booz & Company' },
  { value: 'International Banker', label: 'International Banker' },
  { value: 'ECFR', label: 'ECFR' },
  { value: 'economy', label: 'economy' },
  { value: 'Days Of Year', label: 'Days Of Year' },
  { value: 'oilprice.com', label: 'oilprice.com' },
  { value: 'EIU', label: 'EIU' },
  { value: 'The Jamestown Foundation', label: 'The Jamestown Foundation' },
  { value: 'cloudfront', label: 'cloudfront' },
  { value: 'Wharton', label: 'Wharton' },
  { value: 'Europe in My Region', label: 'Europe in My Region' },
  { value: 'Drydock Magazine', label: 'Drydock Magazine' },
  { value: 'Maplecroft', label: 'Maplecroft' },
  { value: 'ihsmarkit', label: 'ihsmarkit' },
  { value: 'bankofengland', label: 'bankofengland' },
  { value: 'Fitch', label: 'Fitch' },
  { value: 'Elsevier', label: 'Elsevier' },
  { value: 'RUSI', label: 'RUSI' },
  { value: 'Time', label: 'Time' },
  { value: 'Le·gal In·sur·rec·tion', label: 'Le·gal In·sur·rec·tion' },
  { value: 'Manufacturing Operations Technology Viewpoints', label: 'Manufacturing Operations Technology Viewpoints' },
  { value: 'Shenandoah', label: 'Shenandoah' },
  { value: 'WSJ', label: 'WSJ' },
  { value: 'World Health', label: 'World Health' },
  { value: 'globalizationpartners', label: 'globalizationpartners' },
  { value: 'djsresearch', label: 'djsresearch' },
  { value: 'Convenience Store Decisions', label: 'Convenience Store Decisions' },
  { value: 'Guardian', label: 'Guardian' },
  { value: 'Prospects for Development', label: 'Prospects for Development' },
  { value: 'Nature', label: 'Nature' },
  { value: 'About Best Binary Options Strategy', label: 'About Best Binary Options Strategy' },
  { value: 'PriceWaterhouseCoopers', label: 'PriceWaterhouseCoopers' },
  { value: 'Innovations Report', label: 'Innovations Report' },
  { value: 'Virgin Atlantic', label: 'Virgin Atlantic' },
  { value: 'New Security Beat', label: 'New Security Beat' },
  { value: 'The American Prospect', label: 'The American Prospect' },
  { value: 'Brookings Institute', label: 'Brookings Institute' },
  { value: 'ecesr', label: 'ecesr' },
  { value: 'Middle East Eye', label: 'Middle East Eye' },
  { value: 'Stanford News', label: 'Stanford News' },
  { value: 'saltlakecityheadlines', label: 'saltlakecityheadlines' },
  { value: 'Digitalist Magazine', label: 'Digitalist Magazine' },
  { value: 'Koenig Investment Advisory', label: 'Koenig Investment Advisory' },
  { value: 'University of Chicago', label: 'University of Chicago' },
  { value: 'Engineering News', label: 'Engineering News' },
  { value: 'Scientific American', label: 'Scientific American' },
  { value: 'Government of Ireland', label: 'Government of Ireland' },
  { value: 'Real Estate Professional', label: 'Real Estate Professional' },
  { value: 'Zero Hedge', label: 'Zero Hedge' },
  { value: 'Jachin Capital', label: 'Jachin Capital' },
  { value: 'nextbigfuture', label: 'nextbigfuture' },
  { value: 'The Conversation', label: 'The Conversation' },
  { value: 'Sputnik News', label: 'Sputnik News' },
  { value: 'Industrial Control Security', label: 'Industrial Control Security' },
  { value: 'Robothub', label: 'Robothub' },
  { value: 'inputsmonitor', label: 'inputsmonitor' },
  { value: 'Motor Magazine', label: 'Motor Magazine' },
  { value: 'CNNMoney', label: 'CNNMoney' },
  { value: 'Gizmodo Australia', label: 'Gizmodo Australia' },
  { value: 'Resources for the Future', label: 'Resources for the Future' },
  { value: 'IRENA newsroom', label: 'IRENA newsroom' },
  { value: 'Worldly', label: 'Worldly' },
  { value: 'The Nation', label: 'The Nation' },
  { value: 'European Council', label: 'European Council' },
  { value: 'metalprices', label: 'metalprices' },
  { value: 'Institutional Investor', label: 'Institutional Investor' },
  { value: 'Before It\'s News | Alternative News | UFO | Beyond Science | True News| Prophecy News | People Powered News', label: 'Before It\'s News | Alternative News | UFO | Beyond Science | True News| Prophecy News | People Powered News' },
  { value: 'EPA', label: 'EPA' },
  { value: 'Politico', label: 'Politico' },
  { value: 'thespanisheconomy', label: 'thespanisheconomy' },
  { value: 'The Atlantic', label: 'The Atlantic' },
  { value: 'CBO', label: 'CBO' },
  { value: 'Triple Pundit', label: 'Triple Pundit' },
  { value: 'greenerearthnews', label: 'greenerearthnews' },
  { value: 'Innovate UK', label: 'Innovate UK' },
  { value: 'Citibank', label: 'Citibank' },
  { value: 'Canadian Biomass', label: 'Canadian Biomass' },
  { value: 'TeleTrade', label: 'TeleTrade' },
  { value: 'IMF', label: 'IMF' },
  { value: 'Bloomberg Business', label: 'Bloomberg Business' },
  { value: 'Future Market Insights', label: 'Future Market Insights' },
  { value: 'MIT Sloan Management Review', label: 'MIT Sloan Management Review' },
  { value: 'theicct', label: 'theicct' },
  { value: 'South China Morning Post', label: 'South China Morning Post' },
  { value: 'Inside Climate News', label: 'Inside Climate News' },
  { value: 'Freenewspos', label: 'Freenewspos' },
  { value: 'energy news cyprus', label: 'energy news cyprus' },
  { value: 'Foreign Policy', label: 'Foreign Policy' },
  { value: 'CleanTechnica', label: 'CleanTechnica' },
  { value: 'Utility Dive', label: 'Utility Dive' },
  { value: 'The Independent', label: 'The Independent' },
  { value: 'Renewable Energy World', label: 'Renewable Energy World' },
  { value: 'ESPAS', label: 'ESPAS' },
  { value: 'The Market Mogul', label: 'The Market Mogul' },
  { value: 'agriworldsa', label: 'agriworldsa' },
  { value: 'FutureinFocus', label: 'FutureinFocus' },
  { value: 'USDA', label: 'USDA' },
  { value: 'savepassamaquoddybay', label: 'savepassamaquoddybay' },
  { value: 'nbp', label: 'nbp' },
  { value: 'Australian Government', label: 'Australian Government' },
  { value: 'Nation of Change', label: 'Nation of Change' },
  { value: 'Total', label: 'Total' },
  { value: 'Wikipedia', label: 'Wikipedia' },
  { value: 'LiveMint', label: 'LiveMint' },
  { value: 'IRENA', label: 'IRENA' },
  { value: 'ethicalconsumer', label: 'ethicalconsumer' },
  { value: 'dailytexanonline', label: 'dailytexanonline' },
  { value: 'Blue and Green Tomorrow', label: 'Blue and Green Tomorrow' },
  { value: 'The Chirographer', label: 'The Chirographer' },
  { value: 'biologicaldiversity', label: 'biologicaldiversity' },
  { value: 'Oxfam', label: 'Oxfam' },
  { value: 'Planetsave', label: 'Planetsave' },
  { value: 'Gartner', label: 'Gartner' },
  { value: 'globalr2p', label: 'globalr2p' },
  { value: 'Eco-Business.com', label: 'Eco-Business.com' },
  { value: 'Embedded Computing Design', label: 'Embedded Computing Design' },
  { value: 'UNEP', label: 'UNEP' },
  { value: 'farms', label: 'farms' },
  { value: 'McKinsey & Company', label: 'McKinsey & Company' },
  { value: 'khorreports-palmoil', label: 'khorreports-palmoil' },
  { value: 'jeita', label: 'jeita' },
  { value: 'Vox', label: 'Vox' },
  { value: 'Europa', label: 'Europa' },
  { value: 'ethicalmarkets', label: 'ethicalmarkets' },
  { value: 'Cushman & Wakefield Blog', label: 'Cushman & Wakefield Blog' },
  { value: 'Think Progress', label: 'Think Progress' },
  { value: 'Project Syndicate', label: 'Project Syndicate' },
  { value: 'AHDB', label: 'AHDB' },
  { value: 'ETEnergyworld.com', label: 'ETEnergyworld.com' },
  { value: 'EY', label: 'EY' },
  { value: 'Cornell University', label: 'Cornell University' },
  { value: 'the star online', label: 'the star online' },
  { value: 'marketrealist', label: 'marketrealist' },
  { value: 'Transport Evolved', label: 'Transport Evolved' },
  { value: 'Handelsblatt Global Edition', label: 'Handelsblatt Global Edition' },
  { value: 'controleng', label: 'controleng' },
  { value: 'University Chronicle', label: 'University Chronicle' },
  { value: 'LNG', label: 'LNG' },
  { value: 'Innovaro', label: 'Innovaro' },
  { value: 'Future in Focus', label: 'Future in Focus' },
  { value: 'Pickens Plan', label: 'Pickens Plan' },
  { value: 'IEA.org', label: 'IEA.org' },
  { value: 'g7g20', label: 'g7g20' },
  { value: 'Neon Nettle', label: 'Neon Nettle' },
  { value: 'Face2face Africa', label: 'Face2face Africa' },
  { value: 'murc', label: 'murc' },
  { value: 'Energy Tomorrow', label: 'Energy Tomorrow' },
  { value: 'Cii Radio', label: 'Cii Radio' },
  { value: 'IEA', label: 'IEA' },
  { value: 'ISA', label: 'ISA' },
  { value: 'Guarini Center', label: 'Guarini Center' },
  { value: 'BorneoPost Online', label: 'BorneoPost Online' },
  { value: 'Future Earth', label: 'Future Earth' },
  { value: 'Fox Business', label: 'Fox Business' },
  { value: 'Farms.com', label: 'Farms.com' },
  { value: 'What\'s Next', label: 'What\'s Next' },
  { value: 'MAPI', label: 'MAPI' },
  { value: 'Fews Net', label: 'Fews Net' },
  { value: 'Azonano', label: 'Azonano' },
  { value: 'JD Supra', label: 'JD Supra' },
  { value: 'Gas 2', label: 'Gas 2' },
  { value: 'Euler Hermes', label: 'Euler Hermes' },
  { value: 'CCN: Financial Bitcoin & Cryptocurrency News', label: 'CCN: Financial Bitcoin & Cryptocurrency News' },
  { value: 'South Sudan News Agency', label: 'South Sudan News Agency' },
  { value: 'NWF', label: 'NWF' },
  { value: 'Drill or drop?', label: 'Drill or drop?' },
  { value: 'FoodQualityNews.com', label: 'FoodQualityNews.com' },
  { value: 'NY Times', label: 'NY Times' },
  { value: 'Physics World', label: 'Physics World' },
  { value: 'prsync', label: 'prsync' },
  { value: 'TheNews.NG', label: 'TheNews.NG' },
  { value: 'Wall Street Daily', label: 'Wall Street Daily' },
  { value: 'Ocean Acidification', label: 'Ocean Acidification' },
  { value: 'RiskMap 2017', label: 'RiskMap 2017' },
  { value: 'EV Obsession', label: 'EV Obsession' },
  { value: 'amundi', label: 'amundi' },
  { value: 'Finance Magnates', label: 'Finance Magnates' },
  { value: 'Hospitality Trends', label: 'Hospitality Trends' },
  { value: 'edie.net', label: 'edie.net' },
  { value: 'oilvoice', label: 'oilvoice' },
  { value: 'DW.COM', label: 'DW.COM' },
  { value: 'Global Information Inc', label: 'Global Information Inc' },
  { value: 'AllAfrica', label: 'AllAfrica' },
  { value: 'Environmental Leader', label: 'Environmental Leader' },
  { value: 'International Business Times', label: 'International Business Times' },
  { value: 'IBEF', label: 'IBEF' },
  { value: 'MIT Technology Review', label: 'MIT Technology Review' },
  { value: 'Informed Choice Chartered Financial Planners in Cranleigh', label: 'Informed Choice Chartered Financial Planners in Cranleigh' },
  { value: 'nbk', label: 'nbk' },
  { value: 'EE News', label: 'EE News' },
  { value: 'westpandi', label: 'westpandi' },
  { value: 'U.S. Environmental Protection Agency', label: 'U.S. Environmental Protection Agency' },
  { value: 'Planetizen', label: 'Planetizen' },
  { value: 'worldenergy', label: 'worldenergy' },
  { value: 'Newsletter', label: 'Newsletter' },
  { value: 'ogauthority', label: 'ogauthority' },
  { value: 'FAO', label: 'FAO' },
  { value: 'Australian Government Department of Defence', label: 'Australian Government Department of Defence' },
  { value: 'dpaq', label: 'dpaq' },
  { value: 'Wood McKenzie', label: 'Wood McKenzie' },
  { value: 'EIA', label: 'EIA' },
  { value: 'Insurance Journal', label: 'Insurance Journal' },
  { value: 'Gii Research', label: 'Gii Research' },
  { value: 'Critical Threats', label: 'Critical Threats' },
  { value: 'World Bank', label: 'World Bank' },
  { value: 'Energy.gov Website', label: 'Energy.gov Website' },
  { value: 'environmentalpeacebuilding', label: 'environmentalpeacebuilding' },
  { value: 'IASTOPPERS', label: 'IASTOPPERS' },
  { value: 'iMFdirect - The IMF Blog', label: 'iMFdirect - The IMF Blog' },
  { value: 'biomassmagazine', label: 'biomassmagazine' },
  { value: 'McKinsey Quarterly', label: 'McKinsey Quarterly' },
  { value: 'Atlantic Council ', label: 'Atlantic Council ' },
  { value: 'Reuters', label: 'Reuters' },
  { value: 'Business Insider', label: 'Business Insider' },
  { value: 'Activist Post', label: 'Activist Post' },
  { value: 'creamermedia', label: 'creamermedia' },
  { value: 'Imeche', label: 'Imeche' },
  { value: 'Technavio', label: 'Technavio' },
  { value: 'cargill', label: 'cargill' },
  { value: 'European Environment Agency', label: 'European Environment Agency' },
  { value: 'iamericas', label: 'iamericas' },
  { value: 'NDTV', label: 'NDTV' },
  { value: 'The Mainichi', label: 'The Mainichi' },
  { value: 'EGYPS', label: 'EGYPS' },
  { value: 'Aljazeera.com', label: 'Aljazeera.com' },
  { value: 'Global Money Trends Magazine', label: 'Global Money Trends Magazine' },
  { value: 'Business Wire', label: 'Business Wire' },
  { value: 'Media Center ', label: 'Media Center ' },
  { value: 'Bearnobull', label: 'Bearnobull' },
  { value: 'Infracircle', label: 'Infracircle' },
  { value: 'OEM/Lube News', label: 'OEM/Lube News' },
  { value: 'Oil and Gas Journal', label: 'Oil and Gas Journal' },
  { value: 'PR Newswire', label: 'PR Newswire' },
  { value: 'Huffington Post', label: 'Huffington Post' },
  { value: 'THE LEAGUE OF WOMEN VOTERS® OF THE FAIRFAX AREA', label: 'THE LEAGUE OF WOMEN VOTERS® OF THE FAIRFAX AREA' },
  { value: 'Bloomberg New Energy Finance', label: 'Bloomberg New Energy Finance' },
  { value: 'World Energy Report', label: 'World Energy Report' },
  { value: 'Energy Transition Insights', label: 'Energy Transition Insights' },
  { value: 'Sustainable Business', label: 'Sustainable Business' },
  { value: 'Global Risk Insights', label: 'Global Risk Insights' },
  { value: 'OECD', label: 'OECD' },
  { value: 'Politico Europe', label: 'Politico Europe' },
  { value: 'New Zealand Herald', label: 'New Zealand Herald' },
  { value: 'Geopolitical Monitor', label: 'Geopolitical Monitor' },
  { value: 'S&P Global', label: 'S&P Global' },
  { value: 'GlobalData', label: 'GlobalData' },
  { value: 'Bruegel', label: 'Bruegel' },
  { value: 'Zero Hedge', label: 'Zero Hedge' },
  { value: 'MSCI', label: 'MSCI' },
  { value: 'Houston Chronicle', label: 'Houston Chronicle' },
  { value: 'Wall Street Journal', label: 'Wall Street Journal' },
  { value: 'RBC', label: 'RBC' },
  { value: 'S&P', label: 'S&P' },
  { value: 'TheStreet', label: 'TheStreet' },
  { value: 'Gulf News', label: 'Gulf News' },
  { value: 'Lloyd\'s List', label: 'Lloyd\'s List' },
  { value: 'Trend Macro', label: 'Trend Macro' },
  { value: 'Standard & Poor\'s', label: 'Standard & Poor\'s' },
  { value: 'United Nations', label: 'United Nations' },
  { value: 'Canadian Press', label: 'Canadian Press' },
  { value: 'Minneapolis Star Tribune', label: 'Minneapolis Star Tribune' },
  { value: 'The Hindu', label: 'The Hindu' },
  { value: 'Yahoo News', label: 'Yahoo News' },
  { value: 'The Australian', label: 'The Australian' },
  { value: 'Cato Institute', label: 'Cato Institute' },
  { value: 'MarketWatch', label: 'MarketWatch' },
  { value: 'Reuters Breakingviews', label: 'Reuters Breakingviews' },
  { value: 'ProPublica', label: 'ProPublica' },
  { value: 'The Daily Beast', label: 'The Daily Beast' },
  { value: 'FT', label: 'FT' },
  { value: 'Investors Business Daily', label: 'Investors Business Daily' },
  { value: 'RFI', label: 'RFI' },
  { value: 'United Nations Development Programme', label: 'United Nations Development Programme' },
  { value: 'Liberty Tree', label: 'Liberty Tree' },
  { value: 'Bridging World History', label: 'Bridging World History' },
  { value: 'Global Trade Magazine', label: 'Global Trade Magazine' },
  { value: 'The National Interest', label: 'The National Interest' },
  { value: 'Asia Times', label: 'Asia Times' },
  { value: 'Genetic Literacy Project', label: 'Genetic Literacy Project' },
  { value: 'Canada Free Press', label: 'Canada Free Press' },
 { value: 'USAToday', label: 'USAToday' },
  { value: 'C&EN', label: 'C&EN' },
  { value: 'Forbes', label: 'Forbes' },
  { value: 'Journal of Commerce', label: 'Journal of Commerce' },
  { value: 'Minneapolis Star Tribune', label: 'Minneapolis Star Tribune' },
  { value: 'The Globe and Mail', label: 'The Globe and Mail' },
  { value: 'New York Times', label: 'New York Times' },
  { value: 'Asia Pacific Journal', label: 'Asia Pacific Journal' },
  { value: 'Financial Times', label: 'Financial Times' },
  { value: 'NPR', label: 'NPR' },
  { value: 'China Daily', label: 'China Daily' },
  { value: 'The Hill', label: 'The Hill' },
  { value: 'The Telegraph', label: 'The Telegraph' },
  { value: 'The Nation', label: 'The Nation' },
  { value: 'The Times', label: 'The Times' },
  { value: 'BBC', label: 'BBC' },
  { value: 'CNN', label: 'CNN' },
  { value: 'Al Jazeera', label: 'Al Jazeera' },
  { value: 'USA Today', label: 'USA Today' },
  { value: 'NYT', label: 'NYT' },
  { value: 'The New Yorker', label: 'The New Yorker' },
  { value: 'The Independent', label: 'The Independent' }
];
  
  export const COUNTRIES =[
    { value: "Germany", label: "Germany" },
    { value: "Venezuela", label: "Venezuela" },
    { value: "Japan", label: "Japan" },
    { value: "Turkey", label: "Turkey" },
    { value: "Belize", label: "Belize" },
    { value: "South Sudan", label: "South Sudan" },
    { value: "Mali", label: "Mali" },
    { value: "India", label: "India" },
    { value: "South Africa", label: "South Africa" },
    { value: "Qatar", label: "Qatar" },
    { value: "Nigeria", label: "Nigeria" },
    { value: "Austria", label: "Austria" },
    { value: "Kuwait", label: "Kuwait" },
    { value: "Lebanon", label: "Lebanon" },
    { value: "Angola", label: "Angola" },
    { value: "", label: "Unknown" },
    { value: "Iran", label: "Iran" },
    { value: "Denmark", label: "Denmark" },
    { value: "Algeria", label: "Algeria" },
    { value: "Azerbaijan", label: "Azerbaijan" },
    { value: "Russia", label: "Russia" },
    { value: "Australia", label: "Australia" },
    { value: "United States of America", label: "United States of America" },
    { value: "Ukraine", label: "Ukraine" },
    { value: "Burkina Faso", label: "Burkina Faso" },
    { value: "Ghana", label: "Ghana" },
    { value: "Egypt", label: "Egypt" },
    { value: "Gabon", label: "Gabon" },
    { value: "United Kingdom", label: "United Kingdom" },
    { value: "Ethiopia", label: "Ethiopia" },
    { value: "Syria", label: "Syria" },
    { value: "Jordan", label: "Jordan" },
    { value: "Kazakhstan", label: "Kazakhstan" },
    { value: "Mexico", label: "Mexico" },
    { value: "Libya", label: "Libya" },
    { value: "Iraq", label: "Iraq" },
    { value: "Argentina", label: "Argentina" },
    { value: "Greece", label: "Greece" },
    { value: "Indonesia", label: "Indonesia" },
    { value: "Estonia", label: "Estonia" },
    { value: "Spain", label: "Spain" },
    { value: "Saudi Arabia", label: "Saudi Arabia" },
    { value: "Liberia", label: "Liberia" },
    { value: "Brazil", label: "Brazil" },
    { value: "Poland", label: "Poland" },
    { value: "Niger", label: "Niger" },
    { value: "Malaysia", label: "Malaysia" },
    { value: "Canada", label: "Canada" },
    { value: "Pakistan", label: "Pakistan" },
    { value: "Hungary", label: "Hungary" },
    { value: "Oman", label: "Oman" },
    { value: "Colombia", label: "Colombia" },
    { value: "Cyprus", label: "Cyprus" },
    { value: "Norway", label: "Norway" },
    { value: "United Arab Emirates", label: "United Arab Emirates" },
    { value: "Morocco", label: "Morocco" },
    { value: "China", label: "China" }
]

  
  export const END_YEARS = [
    { value: '', label: 'All' },
    { value: '2016', label: '2016' },
    { value: '2017', label: '2017' },
    { value: '2018', label: '2018' },
    { value: '2019', label: '2019' },
    { value: '2020', label: '2020' },
    { value: '2021', label: '2021' },
    { value: '2022', label: '2022' },
    { value: '2024', label: '2024' },
    { value: '2025', label: '2025' },
    { value: '2026', label: '2026' },
    { value: '2027', label: '2027' },
    { value: '2028', label: '2028' },
    { value: '2030', label: '2030' },
    { value: '2034', label: '2034' },
    { value: '2035', label: '2035' },
    { value: '2036', label: '2036' },
    { value: '2040', label: '2040' },
    { value: '2041', label: '2041' },
    { value: '2046', label: '2046' },
    { value: '2050', label: '2050' },
    { value: '2051', label: '2051' },
    { value: '2055', label: '2055' },
    { value: '2060', label: '2060' },
    { value: '2126', label: '2126' },
    { value: '2200', label: '2200' }
  ];
  
  // Add values for Intensity, Likelihood, and Relevance
  export const INTENSITIES = [
    { value: '', label: 'All' },
    { value: '1', label: '1' },
    { value: '2', label: '2' },
    { value: '3', label: '3' },
    { value: '4', label: '4' },
    { value: '6', label: '6' },
    { value: '8', label: '8' },
    { value: '9', label: '9' },
    { value: '10', label: '10' },
    { value: '12', label: '12' },
    { value: '14', label: '14' },
    { value: '15', label: '15' },
    { value: '16', label: '16' },
    { value: '18', label: '18' },
    { value: '20', label: '20' },
    { value: '24', label: '24' },
    { value: '30', label: '30' },
    { value: '32', label: '32' },
    { value: '36', label: '36' },
    { value: '40', label: '40' },
    { value: '48', label: '48' },
    { value: '60', label: '60' },
    { value: '72', label: '72' },
    { value: '96', label: '96' }
];

  
  export const LIKELIHOODS = [
    { value: '', label: 'All' },
    { value: '1', label: '1' },
    { value: '2', label: '2' },
    { value: '3', label: '3' },
    { value: '4', label: '4' }
  ];
  
  export const RELEVANCES = [
    { value: '', label: 'All' },
    { value: '1', label: '1' },
    { value: '2', label: '2' },
    { value: '3', label: '3' },
    { value: '4', label: '4' },
    { value: '5', label: '5' },
    { value: '6', label: '6' },
    { value: '7', label: '7' },
  ];
  